### ISSUE TITLE
Ability to Fuzzy search

### ISSUE THREAD

**Issue by Ranguna** [catgoose/telescope-helpgrep.nvim#3]
From what I could understand, fuzzy searching with live_grep is only possible for searching the current buffer when pressing C+space.

But searching with grep_string should have fuzzy search enabled.

Would it be possible to switch to grep_string instead of live_grep ?

**Comment by catgoose** [comment]
#4 added support for using

`:Telescope helpgrep grep_string` and `require("telescope-helpgrep").grep_string()`

**Comment by Ranguna** [comment]
And it's on the readme, I feel stupid now 🤦

Thanks for the info!

**Comment by catgoose** [comment]
To your defense it wasn't on the read me when you opened the issue. I updated the readme with the PR adding support for grep_string builtin.

**Comment by Ranguna** [comment]
Ah right right. Thanks again, this will help a ton!

**Comment by Ranguna** [comment]
Actually, I just tested this and it's not fuzzy searching yet. Is it because this should be grep_string instead of live_grep ?
https://github.com/catgoose/telescope-helpgrep.nvim/pull/4/files#diff-da8aa6b18b95fc1575f488b249c5303e6c5226c6273fedeb8c2fb650f6d7f3a8R40

**Comment by catgoose** [comment]
Yep, that would be why :D

I pushed a commit to main if you can check if it is working how you expect.

**Comment by Ranguna** [comment]
Now it's perfect

Before:
![image](https://github.com/catgoose/telescope-helpgrep.nvim/assets/5003755/04dee0c8-0d2f-4ff7-b5d7-68a481472268)

After:
![image](https://github.com/catgoose/telescope-helpgrep.nvim/assets/5003755/9f0dd584-d324-4cfe-8459-5494507be1a7)

Thanks again!
